### ISSUE TITLE
auro-button: Updating to 6.3.3 breaks headless chrome tests

### ISSUE THREAD

**Issue by diana-wang** [AlaskaAirlines/auro-button#127]
## Describe the bug
I tried updating from 6.2.0 to 6.3.3, but this broke the headless chrome integration tests. Nothing else was changed
![image](https://user-images.githubusercontent.com/11242098/122996016-33d6c880-d35f-11eb-913d-75c87afb6473.png)

I would not expect all those tests to break simply by updating the version for auro-button.

The tests still work when updating to 6.3.2, so it seems to be something specifically with the 6.3.3 release. I'm unsure if there's another change that I'm supposed to be making in Component Hanger, or a dependency I'm missing.

## To Reproduce
Here is the pipeline with the tests failing: [Component Hanger Build](https://dev.azure.com/itsals/E_Sell_PathtoPurchase/_build/results?buildId=1745886&view=results)

I don't think there's an easy way to reproduce it with just auro-button. The easiest way is to set up Component Hanger repository and run the tests locally.

**Comment by geoffrich** [comment]
I think I know what the issue is here. For now, it seems like you can work around it by installing the following commands (I tested this with the hangar locally):

```
npm i lit-element@latest
npm i lit-html@latest
npm dedupe
```

After that, I was able to successfully run the Headless Chrome tests.

**Comment by geoffrich** [comment]
The root cause is an update to the button's dependencies that required a higher version of lit-html than was installed in the component hangar. There were then 2 versions of lit-html, resulting in the broken button you saw above. See https://github.com/AlaskaAirlines/auro-button/commit/da4edec51e7cb1d50f7d6a2f09f60144960f1b07

I think we can fix this by lowering the required version of lit-html. @blackfalcon I'll be submitting a PR shortly.

**Comment by diana-wang** [comment]
Sweet, thank you @geoffrich! I'll use that for now. Once auro-button is updated I'll update to the newer version with the fix.

**Comment by geoffrich** [comment]
I confirmed that the new version fixes the Component Hangar tests on my local box.
