### ISSUE TITLE
Clearly define hyperlink and button use

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-button#184]
# General Support Request

This is a screenshot from the account management page. A couple of things I want to point out. 

1. I'd really like to discourage developers from doing this pattern. This example is a contrived hyperlink with `role=button` and an icon. Nothing wrong with that, but the tab UI experience is poor. 
2. The `edit` button again is a hyperlink with `role=button`, not to mention it has an underline that does not change state on hover and the color difference is not enough. 

<img width="520" alt="Screen Shot 2022-12-24 at 11 18 30 AM" src="https://user-images.githubusercontent.com/181089/209448930-30a8d693-4258-42a2-884b-0ef067e2becd.png">

## Support request

1. See the code example below, but again this UI should be managed via this button option. 
1. I believe that `<auro-button slim tertiary>Tertiary</auro-button>` is the current ideal solution for replacing the `edit` button? 

#### Example #1 

```html
<auro-button tertiary>
  <auro-icon customcolor category="interface" name="plus-stroke"></auro-icon>
  Add email address
</auro-button>
```

## Possible Solution

There is literally no reason why a developer must redefine a hyperlink to a button resulting in incorrect affordances. 

I'd like to work with the UI leaders to come up with a documentation solution that will easily communicate this directive.

**Comment by leeejune** [comment]
Designers have been advised to use `auro-button` instead of `auro-hyperlink` for these cases, and they have a good understanding of the differences between the two. However, there has been requests about creating a button that looks like what is being shown above: a blue text button with a plus icon.

There needs to be more discussion around the use cases of this button and if we should add it into our design system. We already explored options of having a blue text button, but moved away from the idea after push back about accessibility.

In this case, the designer either needs to comply to the current button design recommendations or make a solid case for a new component idea for Auro.

**Comment by blackfalcon** [comment]
Thanks for the feedback. I leave this in your very capable hands.
