### ISSUE TITLE
Implement icon only feature

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-button#199]
## Is your feature request related to a problem? Please describe.
Design work has been completed per ticket #194.

## Describe the solution you'd like
Updated design work for mobile to be implemented into the component.

Blueprint:
https://www.figma.com/file/CFVIEQkpeykfQejPppBili/Button?node-id=2421-22330&t=gtZn9sU6utaXUakk-4

**Comment by blackfalcon** [comment]
@leeejune I see in the blueprint that the icon has different sizes. This is NOT a concern of the button element. 

@jordanjones243 we already have a modifier attribute for `slim`, has there been a discussion about what attribute will be used to create this new button shape? 

@leeejune I am looking at the button designs and I am curious as to how this was thought of for development. What are the combinations of tokens to be used for this shape?

**Comment by jordanjones243** [comment]
> @leeejune I see in the blueprint that the icon has different sizes. This is NOT a concern of the button element.
> 
> @jordanjones243 we already have a modifier attribute for `slim`, has there been a discussion about what attribute will be used to create this new button shape?
> 
> @leeejune I am looking at the button designs and I am curious as to how this was thought of for development. What are the combinations of tokens to be used for this shape?

I would argue that button should be able to manipulate the different sizes of the icon. The argument is that since the content within the button is slot content, we do not know what content the user with insert within the button. Yet, we have styles that set rules on text of a "default" button (font-size, font-family, etc.). I feel as though as long as we document the proper way the icon button should be used, it should be ok to manipulate the size of the icon within the repo.

I am currently manipulating the size of the icon icons by using an `iconOnly` attribute for the default icon button and then using a class that is applied to the button when the `iconOnly` and `slim` attributes are both present.

**Comment by jason-capsule42** [comment]
I concur with Jordan on this. I would extend the idea that we do have a pattern of formatting slot content by referencing helpText in input/combobox/datepicker where the text entered into the slot is colors based on validity state.

**Comment by blackfalcon** [comment]
It is not appropriate for the parent element to have intimate knowledge of a possible child component's API. The button's sole responsibility is to alter its shape to better fit the content. That should be applicable to any content, not just using an icon. 

If the icon needs to change, the user should apply that at the icon level. Again, this is a feature that can be used in any context, not just auro-button. 

It's not a question of "can we do it?" because we can. It's more of a "should we do it?". Also, this pattern of thought goes against the concept of moving to a more white-label model allowing users more ability to customize in the right places.

**Comment by blackfalcon** [comment]
> I am currently manipulating the size of the icon

@jordanjones243 you are currently working on this?
